In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Zomato-data-.csv")

In [ ]:
df.head(10) #shows first ten rows with name and column

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
5,Timepass Dinner,Yes,No,3.8/5,286,600,Buffet
6,Rosewood International Hotel - Bar & Restaurant,No,No,3.6/5,8,800,Buffet
7,Onesta,Yes,Yes,4.6/5,2556,600,Cafes
8,Penthouse Cafe,Yes,No,4.0/5,324,700,other
9,Smacznego,Yes,No,4.2/5,504,550,Cafes

In [ ]:
df.tail(10) #shows last 10 rows and column

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
138,Sri Murari Family Restaurant,No,No,2.9/5,0,250,Dining
139,Aramane Donne Biriyani,No,No,2.9/5,0,150,Dining
140,Darkolates,No,No,3.3/5,0,200,Dining
141,Swaada Healthy Kitchen,No,No,3.3/5,0,350,Dining
142,Gawdaru Mane Beriyani,No,No,3.3/5,0,300,Dining
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [12]:
df.head(50)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
5,Timepass Dinner,Yes,No,3.8/5,286,600,Buffet
6,Rosewood International Hotel - Bar & Restaurant,No,No,3.6/5,8,800,Buffet
7,Onesta,Yes,Yes,4.6/5,2556,600,Cafes
8,Penthouse Cafe,Yes,No,4.0/5,324,700,other
9,Smacznego,Yes,No,4.2/5,504,550,Cafes
10,Village Café,Yes,No,4.1/5,402,500,Cafes
11,Cafe Shuffle,Yes,Yes,4.2/5,150,600,Cafes
12,The Coffee Shack,Yes,Yes,4.2/5,164,500,Cafes
13,Caf-Eleven,No,No,4.0/5,424,450,Cafes
14,San Churro Cafe,Yes,No,3.8/5,918,800,Cafes
15,Cafe Vivacity,Yes,No,3.8/5,90,650,Cafes
16,Catch-up-ino,Yes,No,3.9/5,133,800,Cafes
17,Kirthi's Biryani,Yes,No,3.8/5,144,700,Cafes
18,T3H Cafe,No,No,3.9/5,93,300,Cafes
19,360 Atoms Restaurant And Cafe,Yes,No,3.1/5,13,400,Cafes
20,The Vintage Cafe,Yes,No,3.0/5,62,400,Cafes
21,Woodee Pizza,Yes,No,3.7/5,180,500,Cafes
22,Cafe Coffee Day,No,No,3.6/5,28,900,Cafes
23,My Tea House,Yes,No,3.6/5,62,600,Cafes
24,Hide Out Cafe,No,No,3.7/5,31,300,Cafes
25,CAFE NOVA,No,No,3.2/5,11,600,Cafes
26,Coffee Tindi,Yes,No,3.8/5,75,200,Cafes
27,Sea Green Cafe,No,No,3.3/5,4,500,Cafes
28,Cuppa,No,No,3.3/5,23,550,Cafes
29,Srinathji's Cafe,No,No,3.8/5,148,550,Cafes
30,Redberrys,Yes,No,4.0/5,219,600,Cafes
31,Foodiction,Yes,No,2.8/5,506,500,other
32,Sweet Truth,Yes,No,3.9/5,35,500,Dining
33,Ovenstory Pizza,Yes,No,3.9/5,172,750,Dining
34,Faasos,Yes,No,4.2/5,415,500,other
35,Behrouz Biryani,Yes,No,3.9/5,230,650,Dining
36,Fast And Fresh,Yes,No,2.8/5,91,400,Dining
37,Szechuan Dragon,Yes,No,4.2/5,1647,600,Dining
38,Empire Restaurant,Yes,No,4.4/5,4884,750,other
39,Maruthi Davangere Benne Dosa,Yes,No,4.0/5,17,150,Dining
40,Chaatimes,Yes,No,3.8/5,133,200,Dining
41,Havyaka Mess,No,No,3.9/5,28,300,Dining
42,McDonald's,Yes,No,3.9/5,286,500,Dining
43,Domino's Pizza,Yes,No,3.9/5,540,800,Dining
44,Onesta,Yes,Yes,4.6/5,2556,600,other
45,Hotboxit,No,No,3.8/5,36,400,Dining
46,Kitchen Garden,Yes,No,3.6/5,244,300,Dining
47,Recipe,Yes,No,4.0/5,804,450,Dining
48,Beijing Bites,Yes,No,3.7/5,679,850,Dining
49,Tasty Bytes,Yes,No,3.1/5,245,300,Dining

In [13]:
df.head(140)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
135,Amma - Manae,No,No,3.1/5,0,400,Dining
136,Sri Sai Tiffannies,No,No,3.3/5,0,150,Dining
137,Hotel Andhra Speices,No,No,2.9/5,0,250,Dining
138,Sri Murari Family Restaurant,No,No,2.9/5,0,250,Dining
139,Aramane Donne Biriyani,No,No,2.9/5,0,150,Dining

In [11]:
df.sample(5)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
108,Naveen Kabab & Biriyani Mane,No,No,3.2/5,9,300,Dining
19,360 Atoms Restaurant And Cafe,Yes,No,3.1/5,13,400,Cafes
97,Ayda Persian Kitchen,No,No,3.7/5,39,950,Dining
103,Floured-Baked With Love,No,No,3.8 /5,45,400,Dining
94,Nandhini Deluxe,No,No,2.6/5,283,600,Dining

In [10]:
df.shape

(148, 7)

In [18]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [22]:
df.dtypes['approx_cost(for two people)'] #data types
#"""age int
#salary float
#name object"""

dtype('int64')

In [24]:
df..info()

SyntaxError: invalid syntax (84944939.py, line 1)

In [26]:
df['approx_cost(for two people)'].describe()

count    148.000000
mean     418.243243
std      223.085098
min      100.000000
25%      200.000000
50%      400.000000
75%      600.000000
max      950.000000
Name: approx_cost(for two people), dtype: float64

In [27]:
df[["name","online_order"]] #selecting

                      name online_order
0                    Jalsa          Yes
1           Spice Elephant          Yes
2          San Churro Cafe          Yes
3    Addhuri Udupi Bhojana           No
4            Grand Village           No
..                     ...          ...
143       Melting Melodies           No
144        New Indraprasta           No
145           Anna Kuteera          Yes
146                 Darbar           No
147          Vijayalakshmi          Yes

[148 rows x 2 columns]

In [28]:
df.iloc[0]

name                            Jalsa
online_order                      Yes
book_table                        Yes
rate                            4.1/5
votes                             775
approx_cost(for two people)       800
listed_in(type)                Buffet
Name: 0, dtype: object

In [30]:
df.iloc[5]

name                           Timepass Dinner
online_order                               Yes
book_table                                  No
rate                                     3.8/5
votes                                      286
approx_cost(for two people)                600
listed_in(type)                         Buffet
Name: 5, dtype: object

In [31]:
df.iloc[2:5,1:3]

  online_order book_table
2          Yes         No
3           No         No
4           No         No

In [32]:
df.sort_values("votes") #ascending sort

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
110,Hari Super Sandwich,No,No,3.2/5,0,200,Dining
107,Coffee Shopee,No,No,3.4/5,0,250,Dining
117,Kulfi & More,No,No,3.4/5,0,150,Dining
118,Kannadigas Karavali,No,No,3.4/5,0,250,Dining
116,Wood Stove,No,No,3.4/5,0,150,Dining
...,...,...,...,...,...,...,...
65,Kabab Magic,Yes,No,4.1/5,1720,400,Dining
44,Onesta,Yes,Yes,4.6/5,2556,600,other
7,Onesta,Yes,Yes,4.6/5,2556,600,Cafes
86,Meghana Foods,Yes,No,4.4/5,4401,600,Dining
38,Empire Restaurant,Yes,No,4.4/5,4884,750,other

In [35]:
df.sort_values("votes",ascending=False) #descending sort

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
38,Empire Restaurant,Yes,No,4.4/5,4884,750,other
86,Meghana Foods,Yes,No,4.4/5,4401,600,Dining
7,Onesta,Yes,Yes,4.6/5,2556,600,Cafes
44,Onesta,Yes,Yes,4.6/5,2556,600,other
65,Kabab Magic,Yes,No,4.1/5,1720,400,Dining
...,...,...,...,...,...,...,...
140,Darkolates,No,No,3.3/5,0,200,Dining
143,Melting Melodies,No,No,3.3/5,0,100,Dining
142,Gawdaru Mane Beriyani,No,No,3.3/5,0,300,Dining
141,Swaada Healthy Kitchen,No,No,3.3/5,0,350,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining

In [37]:
df["revnue"]=df["votes"]*df["approx_cost(for two people)"]
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type),revnue
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet,620000
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet,629600
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet,734400
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet,26400
4,Grand Village,No,No,3.8/5,166,600,Buffet,99600